name: Progressive Deployer

on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
      project_id:
        type: string
        required: true
      region:
        type: string
        required: true
      traffic_shift:
        type: number
        required: true

permissions:
  contents: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Progressive Deployment
        run: |
          echo "Progressively shifting traffic for: ${{ github.event.inputs.service_name }}"
          echo "Project: ${{ github.event.inputs.project_id }}"
          echo "Region: ${{ github.event.inputs.region }}"
          echo "Shifting traffic by: ${{ github.event.inputs.traffic_shift }}%"
